// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nysitlmayxsllduxyuqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55c2l0bG1heXhzbGxkdXh5dXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NjgxNjUsImV4cCI6MjA3NzE0NDE2NX0.f_5tTuy4ercj9M3lovnA9EqvoxcqsWuo3cb1TafkFC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);